name: Build hip-fryer

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - "master"
    tags:
      - "v*"
  pull_request:
    branches:
      - "master"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rust:
    name: Rust checks
    permissions:
      pull-requests: write
      contents: read
    uses: ./.github/workflows/rust.yaml
  build:
    permissions:
      packages: write
      contents: read
    name: Build and push docker image
    uses: ./.github/workflows/build.yaml
    needs: rust
